# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build ISOs 

on:
  push:
    tags:
      - "*"

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Docker container 
        run: |
          docker build --rm -t ash-os:latest .
      - name: Run Docker container 
        run: | 
          docker run -v $(pwd)/out:/build/out --privileged ash-os:latest
      - name: Create ISO release 
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: out/*.iso
